import type { TagEnum } from "./type";

export const tagLabelMap: Record<TagEnum, string> = {
  talks: "Talks",
  media: "Media",
  nextjs: "Next.js",
  "generative-ai": "Generative AI",
  liam: "Liam",
  github: "GitHub",
  valibot: "Valibot",
  dev: "Dev",
  life: "Life",
  job: "Job",
  "desk-setup": "Desk Setup",
  graphql: "GraphQL",
  "findy-tools": "Findy Tools",
  database: "Database",
  gadget: "Gadget",
  typescript: "TypeScript",
  react: "React",
  ruby: "Ruby",
  "route06-tech-blog": "ROUTE06 Tech Blog",
  "route06-radio": "ROUTE06 Radio",
  "timee-product-team-blog": "Timee Product Team Blog",
  "tech-street": "TECH Street",
  zenn: "Zenn",
  qiita: "Qiita",
  note: "note",
};
