on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  vrt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-focal@sha256:9ff84acc199070b47323c250a415aae96bb20a4615f064e58514c938dd46e895

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
      - run: pnpm test:vrt:screenshots
      - uses: lost-pixel/lost-pixel@e04b7ee63557f3fb6f1be867262c84091ca31208 # v3.18.1
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
