on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  vrt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    container:
      image: mcr.microsoft.com/playwright:v1.45.3-focal@sha256:b192fc2de51a106e18daf3e917cb8c0a8f9c060c763225223cf865fddfed5bab

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
      - run: pnpm test:vrt:screenshots
      - uses: lost-pixel/lost-pixel@6c30db12013deca27ce30e7cce32b4fc2aee6f49 # v3.18.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
