on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  vrt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    container:
      image: mcr.microsoft.com/playwright:v1.48.0-focal@sha256:c698a19398954d97dafe493f13a92f09857324cfbe99f1406408e083599e4d0b

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
      - run: pnpm test:vrt:screenshots
      - uses: lost-pixel/lost-pixel@2b638646343cf4335356241dd7399184fa27681b # v3.20.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
