on:
  deployment_status:

jobs:
  vrt:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: lost-pixel/lost-pixel@v3.4.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
