on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  vrt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    container:
      image: mcr.microsoft.com/playwright:v1.45.0-focal@sha256:aaf7bf71469e471d6c4207ae3280d664be37c1a5472533b7ee74ee4741742044

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
      - run: pnpm i
      - run: pnpm --filter web test:vrt:screenshots
      - uses: lost-pixel/lost-pixel@e3c935b461073034e8a2e2a773f8b07abf0ee858 # v3.17.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
