name: VRT

on:
  deployment_status:

jobs:
  vrt:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    outputs:
      failed: ${{ steps.compare.outcome == 'failure' }}
    container:
      image: mcr.microsoft.com/playwright:v1.40.1-focal

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4.0.1
        with:
          node-version-file: .node-version
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.2
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-setup-pnpm
          restore-keys: |
            ${{ runner.os }}-pnpm-store-setup-pnpm
      - run: pnpm install
        shell: bash

      - run: pnpm --filter web test:vrt:screenshots
        env:
          BASE_URL: https://www.mh4gf.dev/

      - run: pnpm --filter web test:vrt:compare
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
        id: compare
        continue-on-error: true

      - name: Upload failed screenshots
        if: steps.compare.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: vrt-failed-screenshots-${{ github.sha }}
          path: apps/web/test-results/

      - name: Set failure output
        if: steps.compare.outcome == 'failure'
        run: echo "{failed}={true}" >> $GITHUB_OUTPUT

  comment-failed-result:
    needs: vrt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write

    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: finder

      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ needs.vrt.outputs.failed == 'true' }}
        with:
          number: ${{ steps.finder.outputs.pr }}
          message: |
            VRTが失敗しました :sob:
            差分をダウンロードし確認してください: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            commit hash: ${{ github.sha }}

      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ needs.vrt.outputs.failed != 'true' }}
        with:
          number: ${{ steps.finder.outputs.pr }}
          message: |
            VRTの差分はありませんでした :tada:
            commit hash: ${{ github.sha }}
