name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  GITHUB_TOKEN: ${{ secrets.MH4GF_PAT }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
      - run: pnpm build:contentlayer
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble@sha256:6446946a1d9fd62d9ae501312a2d76a43ee688542b21622056a372959b65d63d
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
      - run: pnpm test:vitest
